export const REQUEST_TOPICS = 'REQUEST_TOPICS';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const TOPICS_GET_REQUEST = 'TOPICS_GET_REQUEST';

export const SHOW_SIGNGIN_MODAL = 'SHOW_SIGNGIN_MODAL';
export const CLOSE_SIGNGIN_MODAL = 'CLOSE_SIGNGIN_MODAL';
export const CLEAR_SIGNGIN_MODAL = 'CLEAR_SIGNGIN_MODAL';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';

export const GET_TOPIC = 'GET_TOPIC';
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE';

